### ISSUE TITLE
dace program cant use the data returned by dace program

### ISSUE THREAD

**Issue by baaiy0610** [spcl/dace#1045]
**Describe the bug**
When I pass the return value of a dace into the dace function, the result produced is an error

**To Reproduce**
1. Run the code
2. look the result and see the error

**Expected behavior**
a = [1, 1, 1] b = [2, 2, 2 ]
c = a + b = [3, 3, 3]
d = a + c = c + a = [4, 4, 4]
![error](https://user-images.githubusercontent.com/53456502/177653597-d5d768d0-073a-4af8-85a7-e8384336d529.png)

**Comment by tbennun** [comment]
Thanks for reporting!

Return-value arrays used to be reallocated every call, except if the program was explicitly precompiled. In that case the documentation mentions that the arrays for the return values are retained across calls. This is done to save time on allocating arrays every time the function is called (what's happening here is a data race - the same array is used both as `a` and as `c` at the same time).

For some reason, return value caching now also happens when calling `@dace.program` functions directly. We will look into this.

**Comment by tbennun** [comment]
@baaiy0610 Unfortunately, I cannot reproduce the issue with the latest `master` branch. Could you rerun it?

**Comment by baaiy0610** [comment]
@tbennun Hi, everything is fine now! thanks a lot
