### ISSUE TITLE
Test requirements are not represented in requirements files

### ISSUE THREAD

**Issue by jdahm** [spcl/dace#1102]
**Describe the bug**
```
$ git grep scipy
```
shows some tests require `scipy`, but no requirements files include that dependency. As a result, running `pytest tests/` fails since it cannot import scipy.

Perhaps this is a misunderstanding of where the requirements are listed. Is there a spot I'm missing?

**Comment by alexnick83** [comment]
You can install requirements for testing dace by executing `python -m pip install .[testing]` from your dace folder. This will install `coverage`, `pytest-cov`, `scipy`, `absl-py`, `opt_einsum`, `pymlir`, and `click`. This is not a complete list; for example, `mpi4py` is missing due to its dependency on an MPI library. Updated documentation that includes all these missing bits and pieces is coming soon™.

**Comment by jdahm** [comment]
Oh, I missed the `testing` extra. Sorry for the noise!
