### ISSUE TITLE
DaCe returns different array than expected

### ISSUE THREAD

**Issue by TheRand0m1z3r** [spcl/dace#1184]
**Describe the bug**
For some reason, using the same (binning) code twice gives me different results. The results are compared to the same unparalleled (and slower) code and do not come out the same.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run [g_r.py.txt](https://github.com/spcl/dace/files/10454330/g_r.py.txt) using DaCe's master branch
2. See, using matplotlib the differences in the returned arrays
3. See error

**Expected behaviour**
We'd expect that both using Dace, and the unparalleled version would return the same arrays.

**Desktop (please complete the following information):**
 - Windows 10
- DaCe's master branch

Thanks in advance for the help!

**Comment by alexnick83** [comment]
The main issue is in `compute_sq` and how it is called:
- In line 672, because `R` is initialized to `0`, it has an integer datatype. Scalar variables in DaCe will not change datatype when reset. In other words, `R`'s datatype **will not** switch to float in line 678. You can easily solve this issue by setting `R = 0.0`.
- In line 405, `compute_sq` is auto-optimized and specialized, i.e., the internal symbol `L` is fixed to the initial value `n = 1000`. This may be a bug, since `r_mat` has `n` rows, the number of which differs every time the outer method is called (@tbennun may you can check if this the intended behavior). In any case, you can stop specialization of `L` by including it in the call as follows: `R[it], S_Q[it, :] = compute_sq(q, S_Q_pretemp, r_mat, L=n)`.

Another issue concerns the `V` symbol, which is passed to `numpy.random.randint`. The default datatype for symbols is int32. However, `numpy.random.randint` expects int64. On my system the program will not work unless I change line 9 to `V = dc.symbol('V', dc.int64)`

With the above changes, the output plots looks similar, although I didn't check the values themselves.

**Comment by TheRand0m1z3r** [comment]
Thank you very much!
