### ISSUE TITLE
profiling SDFG issues cryptic TypeError

### ISSUE THREAD

**Issue by rohanrayan** [spcl/dace#1381]
**Describe the bug**
I am trying to perform a profiling operation (as shown in the examples here: https://nbviewer.org/github/spcl/dace/blob/master/tutorials/benchmarking.ipynb)

I have a simple matrix addition example which I auto_optimize, compile to an SDFG and load it again (not using the to_sdfg() directly as it ignores the auto_optimize flag)

I then try to run the profiling code but I get a cryptic TypeError.

**To Reproduce**
[profiling_bug.zip](https://github.com/spcl/dace/files/12799699/profiling_bug.zip)

I am attaching an ipnb to reproduce the behavior. The issue occurs in the last step when trying to run the instrumented SDFG.

**Expected behavior**
I expect the instrumentation to process and generate a JSON file with the results.

**Screenshots**
Attached in the .zip file

**Desktop (please complete the following information):**
dace v0.14.3

**Comment by alexnick83** [comment]
Python doesn't have scopes like, e.g., C++. The quick solution is to **NOT** use `m` and `n` in your following code, because you use them earlier and later as integers:
```python
# Get all maps
maps = [n for n, _ in madd_sdfg.all_nodes_recursive() if isinstance(n, dace.nodes.MapEntry)]

# Instrument with wall-clock timer
for m in maps:
    m.instrument = dace.InstrumentationType.Timer
```

In the above code, the line `for m in maps:` does not create a new `m` variable but it replaces the existing `m` variable, previously defined as an integer. Furthermore, after completing the for-loop, `m` will hold the last element of `maps,`, i.e., the last MapEntry node you found in the first line in the above snippet.

For completeness, the TypeError is caused directly by the above. In the DaCe program that you wrote, you defined `m,` and `n` as integers, but you pass MapEntry nodes for execution. To execute the program, DaCe must first "marshal" the Python data to C/C++ compatible data. In the process, an attempt was made to convert the passed MapEntry node to an integer, which obviously failed. The attempt was made through Python's builtin method `int` that accepts only "a string, a bytes-like object or a number," as explained in the raised TypeError.

I hope this helps!

**Comment by rohanrayan** [comment]
Thanks. That helps fix the issue
