### ISSUE TITLE
dace fails to compile a function with nested loops

### ISSUE THREAD

**Issue by rohanrayan** [spcl/dace#1550]
**Describe the bug**
I have a simple program below:

```
N = dace.symbol('N')
@dace.program(auto_optimize=True)
def error_fn_dace(L:dace.float64[N, N], index:dace.uint64, active_size:dace.uint64):
    for i in range(index, active_size - 1):
        L[i + 1][i] = 1.0

        for j in range(i, active_size-1):
            L[j + 1][i] = 2.0
```

When trying to compile this function, I get an error, but if I change the j for loop to:
`for j in range(i, active_size)`
it compiles. 

Could you please let me know if I am doing something wrong? 

**To Reproduce**
1. I am using dace v0.15.1
2. I have attached the python code which produces the error
[error_report.txt](https://github.com/spcl/dace/files/14647667/error_report.txt)

**Expected behavior**
The compilation should not fail

**Desktop (please complete the following information):**
 - OS: [Linux]
 - DaCe v0.15.1

**Comment by tbennun** [comment]
Thanks! This is an auto-optimize related failure, which is now fixed in #1746.

There was actually another issue with the code: using `uint64` for the bounds and subtracting one would actually convert it to a `float64`, according to NumPy 1 rules:
```python
>>> np.uint64(1) + 1
2.0
```

So the correct code would be:
```python
    @dace.program(auto_optimize=True)
    def tester(L: dace.float64[N, N], index: dace.uint64, active_size: dace.uint64):
        for i in range(index, active_size - 1):
            L[i + 1][i] = 1.0

            for j in range(i, dace.int64(active_size - 1)):
                L[j + 1][i] = 2.0
```

If you change both arguments to `dace.int64`, the code runs even faster.
