### ISSUE TITLE
over-sized allocation of arrays for dace tensor with only shape argument

### ISSUE THREAD

**Issue by xyuan** [spcl/dace#1628]
This issues comes from PACE application code, for details, please see this PR https://github.com/GridTools/gt4py/pull/1554

this problem comes from the following code, 

if strides is not None and shape is not None and total_size is None:
        # Compute the minimal total_size that could be used with strides and shape
        self.total_size = sum(((shp - 1) * s for shp, s in zip(shape, strides))) + 1
    else:
        self.total_size = total_size or _prod(shape)

when the shape is provided in the call argument, the total_size is calculated using, 
      self.total_size = sum(((shp - 1) * s for shp, s in zip(shape, strides))) + 1

which gives over-sized memory allocation. This is not right in pace, and not cache friendly, although the final results are identical. Bringing up this issue in dace developer community to understand, whether there is special reason to calculate the total_size, or this is a bug/mistake. if this is bug/mistake, so dace can have a fix, and we don't have to make change in the application side.

this issue is easy to have a reproducer, simply to use the shape argument instead of total_size to initialize a tensor, we will find the allocated memory is much larger than the real size you plan to.

**Comment by alexnick83** [comment]
Thank you for  reporting this. Could you provide a concrete example where this formula leads to an over-sized memory allocation? Are you perhaps using custom strides?

**Comment by xyuan** [comment]
the issue is from this line of code, 

_self.total_size = sum(((shp - 1) * s for shp, s in zip(shape, strides))) + 1_

the total_size is calculated by sum over (shp-1)*s, actually, the total_size is only dependent on the shape. strides shouldn't contribute to the calculation of total_size as we used in our c++ kokkos code.

**Comment by xyuan** [comment]
if you still want a concrete case for this issue, I can make one for sure.

**Comment by alexnick83** [comment]
A concrete example would help to better understand the issue because, at least with the default way of computing the strides in DaCe, the formula above should provide an exact size (same as product of the extents in the shape). In DaCe, the strides are defined in number of elements and the lowest stride is 1. This definition may not match your expectation, for example NumPy uses number of bytes.

**Comment by xyuan** [comment]
interesting, so for multidimensional tensor, did you mean the stride is still one? I understand that the lowest stride is always unit

**Comment by alexnick83** [comment]
If you have an Array with shape (5, 3, 2, 6) the default strides in DaCe, assuming C-ordering, are (36, 12, 6, 1). This is the number of values you need to move your pointer  forward to access the next element per dimension.

**Comment by xyuan** [comment]
based on this data, the tensor total_size=5*36+3*12+2*6+1*6+1 > 5*3*2*6

**Comment by alexnick83** [comment]
The formula computes the total size as `(5-1)*36 + (3-1)*12 + (2-1)*6 (6-1)*1 + 1`

**Comment by tbennun** [comment]
The total size is computed as "the largest possible accessible index" according to the formula. So regardless of the actual size this becomes a lower bound on the size of the array (because you still want to be able to access `a[-1, -1, ..., -1]` with your strides).

That is, of course, if the total size is not given to dace.

**Comment by xyuan** [comment]
yes, you are right, thanks very much
