### ISSUE TITLE
DIODE broken after serialization cleanup

### ISSUE THREAD

**Issue by tbennun** [spcl/dace#25]
**Describe the bug**
DIODE does not interact well with SDFGs following the merge of the `serialization_cleanup` branch.

Among broken features:
* Add new symbols/arrays does not work
* Properties of graph elements and transformations do not show up
* Symbol types may change during serialization/deserialization and disallow transformation/running (Example: filter.py)

**To Reproduce**
1. Run DIODE
2. Open any file (gemm.py, filter.py for the third broken feature)
3. For each problem:
    * Problem 1: In the properties window, type a name and click add symbol / add array. An exception from Python is raised.
    * Problem 2: Click any graph element (state, node). No properties show up in the properties pane.
    * Problem 3: Run filter.py, apply any transformation and revert. Python exceptions are raised due to a conversion from float to int during serialization/deserialization.

**Comment by definelicht** [comment]
@tbennun Not failing for default properties doesn't necessarily solve the issue, since a lot of our defaults come from the constructor arguments, not from the properties. For example, this did not fix the array, because `allow_conflicts` does not have a default value (rather, the constructor has a default value, which it assigns to the property).

I guess we can add defaults for these properties, but we might get similar errors for other objects in the future.

**Comment by tbennun** [comment]
@definelicht in the other branch I added defaults for all properties

**Comment by definelicht** [comment]
I'm not convinced that this is the correct solution: we are essentially duplicating functionality by having a default in the constructor, and a default in the properties. This means that they could potentially mismatch, giving you different default objects depending on whether you construct them in Python or from DIODE :-/ We are abusing serialization to do construction

**Comment by tbennun** [comment]
Fixed
