### ISSUE TITLE
Code style issue: staticmethod, classmethod

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#408]
**Google styleguide**

> Never use staticmethod
https://google.github.io/styleguide/pyguide.html#217-function-and-method-decorators

**Example**

https://github.com/spcl/dace/blob/a3a1fb9b60d2414bb90a5837f83d30e4a0182b43/dace/transformation/dataflow/redundant_array.py#L29

**Possible solution**

Define outside of classes, if necessary assign to the class member

```
def bar():
    print("Good")

class ABC:
    foo_good = bar 

    @staticmethod
    def foo_bad():
        print("Bad")

ABC.foo_bad()
ABC.foo_good()
```

**Google styleguide**

> Use classmethod only when writing a named constructor or a class-specific routine that modifies necessary global state such as a process-wide cache.
https://google.github.io/styleguide/pyguide.html#2174-decision

**Example**

https://github.com/spcl/dace/blob/22fd2d20b896b58a39f5dedc698d0807296767a5/dace/transformation/transformation.py#L174

**Possible solution**

Define function outside of class

**Comment by tbennun** [comment]
I agree with removing `staticmethod`s at every place that is not a registered subclass e.g., Transformations:
* We have about ~30 (if not more) of them and they are user extensible
* You need to have a function for each one (e.g., `MapFusion.can_be_applied`)
* A Transformation object is attached to an existing match

TensorFlow (a Google project), for example, uses static methods plentily when dealing with registered subclasses in C++ (their operators). Same for PyTorch and autograd functions. I do not see a difference here. 

The possible solution mentioned here is not supported by the Google style guidelines. Even if it was, it would make the code harder to read as you would need to go to the class, see which method you use for `can_be_applied`, then scroll up/down/go-to-definition to find that function, instead of just having that function within the class.

As for making `can_be_applied` a proper method, see the Cons section of the Google style guidelines: using static methods is a good way to avoid users accidentally storing state `self.x` in a match object as well (this was done in the past), since the `can_be_applied` function is called on each matching subgraph you can get invalid data there. 


I'm also ok with replacing staticmethods with classmethods.

**Comment by alexnick83** [comment]
### staticmethod
It is true that in Python, there is no necessity to use `@staticmethod.` This is because it is perfectly fine to just throw your "static" methods in the module. I believe that this is related to #410. If you do `import dace.transformations.transformations as tf,` then it is not very different to call `tf.can_be_applied` or `tf.Transformations.can_be_applied`. However, "static" methods are prevalent in almost all programming languages. I am not sure why they would be considered bad in Python. They are just a tool to organize methods inside related classes.

@tbennun Replacing static methods with class methods would be wrong. Class methods have a specific purpose.

### classmethod
The use of `@classmethod` presented above is valid. You want the method `apply_to` of the super-class `Transformation` to specialize based on the exact sub-class through which the method is being called. This is exactly the purpose of the `@classmethod` decorator, no? I wouldn't be surprised though if we use `@classmethod` in cases where it doesn't make sense. In such cases, yes, the decorator should be removed.

**Comment by tbennun** [comment]
I actually learned about `classmethod`s while writing this function. Found it very useful!

**Comment by tbennun** [comment]
@alexnick83 11 occurrences of `@classmethod`, all of them justified (when you need the class itself, like `from_json` and `apply_to`).
