### ISSUE TITLE
Code style issue: docstrings and API design

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#412]
**Google style guide**

> A docstring should give enough information to write a call to the function without reading the function’s code.
https://google.github.io/styleguide/pyguide.html#383-functions-and-methods

**Example**

Function inputs (`where`) are difficult to figure out
https://github.com/spcl/dace/blob/22fd2d20b896b58a39f5dedc698d0807296767a5/dace/transformation/transformation.py#L447 
Example use
https://github.com/spcl/dace/blob/6e91853c0f4fa06ebdd8672e52b478f9b7219873/tests/transformations/map_interchange_test.py#L35 
Evidence that such use can't be understood even by looking at the transformation definition
https://github.com/spcl/dace/blob/6e91853c0f4fa06ebdd8672e52b478f9b7219873/dace/transformation/dataflow/map_interchange.py#L22

**Solution**

Design interfaces that accept a fixed (non arbitrary) set of parameters, each of them with fixed type (or ducktype, or protocol).

**Comment by tbennun** [comment]
Great find! Please add an example use to the documentation as part of a PR. Any other instances are appreciated.

The names of fields in the transformation (e.g., outer_map_entry, inner_map_entry) should be clearly documented in the respective Transformation subclass docstring. If not, we should take care of that.

Your solution is already done in `apply_to`: the types of `where` are written down clearly in the documentation and type hints.

The evidence you present, however, is a symptom of something else: a weakness of the current Transformation "static field" API to define pattern-matching nodes with names. We cannot use a static class like `_outer_map_entry = nodes.MapEntry`, because then you cannot use more than one of them in the same pattern (we tried this approach), and so the only way is to create the object itself. We just plugged in some default arguments here (Map and MapEntry do lack documentation of their `__init__` method).

One possible replacement is to make it as an argument of a new class, such as a PatternNode. For example
`outer_map_entry = PatternNode(nodes.MapEntry)`
and then it would be simpler. @alexnick83 what do you think of my proposal?

**Comment by definelicht** [comment]
Generally I agree we need more docstrings, but I also fucking hate writing them, so I understand why we don't (their syntax is soooo verbose and annoyingly formatted). This needs to be solved on a case-by-case basis.

**Comment by alexnick83** [comment]
I would argue that this interface actually accepts a fixed set of parameters with a fixed type. It takes an SDFG object and a dictionary with the values for transformation-specific variables. The type annotation is wrong, though. It should be `Dict[Any, Any]`, not just `Any`. I think the issue in this particular example is different:
- The `options` parameter is passed in expanded (`**`) form. I suppose this has been done for convenience, but maybe it is more confusing that way? Perhaps it would be cleaner if you had to pass a dictionary object.
- The `options` parameter was added in the first place (a long time ago) to handle all transformations through a single automatic mechanism. The case where the user constructs this dictionary manually was not considered in the initial design.
- The actual options/class variables etc. of the transformations are not explicitly documented. We need for each transformation a short docstring with an example `options` dictionary that can be passed to the `apply_to` method.

@tbennun I think it would be helpful so people do not have to guess how to create "empty" (but not really empty) nodes of a specific type.
