### ISSUE TITLE
Missing python packages for test_all.sh

### ISSUE THREAD

**Issue by andreaskuster** [spcl/dace#445]
**Describe the bug**
The packages  `opt_einsum`, `pytest` and `mpi4py` are missing in  `requirements.txt` (i.e. `test_all.sh` fails locally with error messages indicating that the dependency couldn't be found.

**To Reproduce**
1. install pip packages: i.e. `python3 -m pip install -r requirements.txt` (local environment)
2. run all tests: i.e. `./test_all.sh`

**Desktop (please complete the following information):**
 - OS: `Ubuntu 20.04.1 LTS`

**Solution**
add `opt_einsum`, `pytest` and `mpi4py` to `requirements.txt`

**Comment by tbennun** [comment]
Well yes, for that you need to install the [testing] optional requirement, since it's not required by dace but only the tests.

Please use `pip install ".[testing]"` or `dace[testing]`

See https://github.com/spcl/dace/blob/master/setup.py#L69 and https://github.com/spcl/dace/blob/master/.travis.yml

for testing environment setup.
