### ISSUE TITLE
Variables inside np.array is not supported

### ISSUE THREAD

**Issue by huanglangwen** [spcl/dace#942]
**Describe the bug**
Creating a numpy array with variables instead of literals lead to compile errors in dace program. Current workaround is to create a constant numpy array and assign each components manually which is much longer.

**To Reproduce**
```python
@dace.program
def test_nparray(a: dace.float64[3]):
    b = np.array([a[0]*a[1], a[2], a[0]+1])
    return b

test_nparray(np.zeros(3))
```

**Comment by alexnick83** [comment]
`np.array` inside a DaCe program is supported only with constant values. There is no check though on the values passed, which is why it doesn't trigger an error in the frontend (which would be the correct behavior). Apart from finding a way to trigger an appropriate error, supporting the above use case does not seem too hard, but it might open a big can of worms (e.g., assigning values with comprehensions). It might be possible though with some new developments in the preprocessor.
