### ISSUE TITLE
interleave operation in the image

### ISSUE THREAD

**Issue by shiruizhao** [spcl/dace#968]
In the Markov Random Filed application, one of the core operation is to read the neighbor nodes, and do the computing. I noticed after apply MapUnroll transformation, it will generate 16 blocks in the SDFG files, however, only 8 of them works.
1. I am curious that whether Dace can simplify the graph to make the FPGA use less resource by utilize the condition info?
2. After MapUnroll, we can see that some of the tasklets have the same input and same operation, is there some transformation methods existed to merge the repeated tasklets?
To reproduce the problem, you can run the notebook [mrf.zip](https://github.com/spcl/dace/files/8205783/mrf.zip).
```
@dace.program
def interleave_compute(A: dace.int64[4, 4], B: dace.int64[4,4]):
    for i, j in dace.map[0:4, 0:4]:
        if(i%2==0 and j%2==0) or (i%2==1 and j%2==1):
            if(i != 0):
                B[i, j] += A[i-1, j]
            if(j != 0):
                B[i, j] += A[i, j-1]
            if(i != 3):
                B[i, j] += A[i+1, j]
            if(j != 3):
                B[i, j] += A[i, j+1]
```

Thanks!

**Comment by alexnick83** [comment]
1. To some degree, yes, although you may have to use the SDFG API and there are some limitations. An example code that should reasonably clean-up your program above is the following:
```python
import dace
from numbers import Number
from dace.transformation.dataflow import MapUnroll
from dace.transformation.interstate.state_elimination import DeadStateElimination

sdfg = interleave_compute.to_sdfg(simplify=True)
sdfg.apply_transformations(MapUnroll)
sdfg.simplify()

# The following code propagates constant mappings of the form {'i': 0, 'j': 1} 
for nsdfg in sdfg.all_sdfgs_recursive():
    if nsdfg is sdfg:
        continue
    mapping = nsdfg.parent_nsdfg_node.symbol_mapping
    for k, v in mapping.items():
        if isinstance(v, Number) or (isinstance(v, str) and isinstance(eval(v), Number)):
            nsdfg.replace(k, v)
sdfg.simplify()

# Removes states that are unreachable
sdfg.apply_transformations_repeated(DeadStateElimination)
sdfg.simplify()
```

2. Since these identical tasklets exist in different nested SDFGs, I don't see an easy way to merge them; at least not without extensive manual editing of the graph.

It appears that you are working with stencil codes. In such a case, it may be worth to check whether it is possible to rewrite your code in a way that avoids the conditionals in the first place. You can look at some jacobi-2d examples (there is one in `tests/npbench/jacobi_2d_test.py`), where the matrices have two extra elements in each dimension for the boundary conditions. Furthermore, if you are interested in running stencil codes on FPGAs, you may want to have a look into [stencilflow](https://github.com/spcl/stencilflow), which is built on top of DaCe.
